# Generated by Django 6.0.2 on 2026-03-26 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='latestUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
