# Generated by Django 6.0.2 on 2026-04-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='retention_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('LOGIN', 'Login'), ('REGISTER', 'Register')], max_length=50),
        ),
    ]
