# Generated by Django 6.0.2 on 2026-04-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0004_conversation_retention_days_alter_log_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('LOGIN', 'Login'), ('REGISTER', 'Register'), ('DELETE_SMS', 'DELETE_SMS'), ('LOGOUT', 'LOGOUT'), ('DELETE_CONVO', 'DELETE_CONVO')], max_length=50),
        ),
    ]
