# Generated by Django 6.0.2 on 2026-04-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0005_alter_log_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('highly_sensitive', 'Highly Sensitive')], default='normal', max_length=20),
        ),
    ]
