# Generated by Django 6.0.2 on 2026-04-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_userkemkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationKey',
        ),
    ]
