name: LockTalk Documentation
on:
  push:
    branches: ["main", "milestone5", "DocumentationBranch"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Only needed here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools
        working-directory: ./frontend
        run: |
          sudo apt-get update && sudo apt-get install -y doxygen
          npm install

      - name: Build TypeDoc
        working-directory: ./frontend
        run: npx typedoc --options ./typedoc.json --tsconfig ./tsconfig.app.json --out ../deploy/frontend

      - name: Create Deploy
        run: mkdir -p deploy/backend/

      - name: Build Doxygen
        run: doxygen Doxyfile

      - name: Prepare Landing Page
        run: cp documentation-landing-page.html ./deploy/index.html

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Needed to publish Pages
      id-token: write   # Required for OIDC auth
    environment:
      name: github-pages
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4